import { DUE_DATA_JSON_SCHEMA } from "./due.js";
import type { NodeType, RelationType } from "./types.js";

/** area → project → goal → habit | task */
export const SPINE_DIAGRAM = "area → project → goal → habit | task";

export const SPINE_TYPE_SLUGS = ["area", "project", "goal", "habit", "task"] as const;
export const ARTIFACT_TYPE_SLUGS = [
  "lesson",
  "person",
  "company",
  "journal",
  "idea",
  "note",
  "trip",
  "decision",
] as const;

export const SEED_NODE_TYPES: readonly NodeType[] = [
  {
    slug: "area",
    label: "Area",
    description: "Spine root. A life domain and what you value (Health, Work, Family, …).",
    kind: "spine",
    parent_types: [],
    json_schema: null,
    is_system: true,
  },
  {
    slug: "project",
    label: "Project",
    description: "A bounded effort that lives under an area.",
    kind: "spine",
    parent_types: ["area"],
    json_schema: null,
    is_system: true,
  },
  {
    slug: "goal",
    label: "Goal",
    description:
      "An outcome a project is aiming at. Optional data.due is an ISO date (YYYY-MM-DD).",
    kind: "spine",
    parent_types: ["project"],
    json_schema: DUE_DATA_JSON_SCHEMA,
    is_system: true,
  },
  {
    slug: "habit",
    label: "Habit",
    description:
      "A repeating practice under a goal. Frequency and tracking live on the node data object.",
    kind: "spine",
    parent_types: ["goal"],
    json_schema: null,
    is_system: true,
  },
  {
    slug: "task",
    label: "Task",
    description: "A discrete action under a goal. Optional data.due is an ISO date (YYYY-MM-DD).",
    kind: "spine",
    parent_types: ["goal"],
    json_schema: DUE_DATA_JSON_SCHEMA,
    is_system: true,
  },
  {
    slug: "lesson",
    label: "Lesson",
    description: "Something learned. May hang under an area, project, or goal.",
    kind: "artifact",
    parent_types: ["area", "project", "goal"],
    json_schema: null,
    is_system: true,
  },
  {
    slug: "person",
    label: "Person",
    description: "A person. Typical target of the about relation.",
    kind: "artifact",
    parent_types: [],
    json_schema: null,
    is_system: true,
  },
  {
    slug: "company",
    label: "Company",
    description: "An organization (employer, vendor, school, …).",
    kind: "artifact",
    parent_types: [],
    json_schema: null,
    is_system: true,
  },
  {
    slug: "journal",
    label: "Journal",
    description: "A dated reflection or log entry.",
    kind: "artifact",
    parent_types: [],
    json_schema: null,
    is_system: true,
  },
  {
    slug: "idea",
    label: "Idea",
    description: "A spark to capture before it has a home on the spine.",
    kind: "artifact",
    parent_types: [],
    json_schema: null,
    is_system: true,
  },
  {
    slug: "note",
    label: "Note",
    description: "Universal capture sink when no more specific type fits yet.",
    kind: "artifact",
    parent_types: [],
    json_schema: null,
    is_system: true,
  },
  {
    slug: "trip",
    label: "Trip",
    description:
      "A journey. Motivating payload example: store an HTML itinerary (text/html, inline) and re-show it as HTML.",
    kind: "artifact",
    parent_types: [],
    json_schema: null,
    is_system: true,
  },
  {
    slug: "decision",
    label: "Decision",
    description: "A choice that was made. May hang under an area, project, or goal.",
    kind: "artifact",
    parent_types: ["area", "project", "goal"],
    json_schema: null,
    is_system: true,
  },
];

export const SEED_RELATION_TYPES: readonly RelationType[] = [
  {
    slug: "child_of",
    label: "Child of",
    description:
      "Hierarchy placement. Source is the child; target is the parent. At most one child_of per source node. Allowed parents come from the source type's parent_types — including types you add with manage_type.",
    kind: "hierarchy",
    source_types: [],
    target_types: [],
    is_symmetric: false,
    semantic_parent_slug: null,
    is_system: true,
  },
  {
    slug: "relates_to",
    label: "Relates to",
    description: "Generic associative link. Any type to any type. Symmetric.",
    kind: "associative",
    source_types: [],
    target_types: [],
    is_symmetric: true,
    semantic_parent_slug: null,
    is_system: true,
  },
  {
    slug: "supports",
    label: "Supports",
    description: "Source supports a spine node (area, project, goal, habit, or task).",
    kind: "associative",
    source_types: [],
    target_types: [...SPINE_TYPE_SLUGS],
    is_symmetric: false,
    semantic_parent_slug: "relates_to",
    is_system: true,
  },
  {
    slug: "inspired_by",
    label: "Inspired by",
    description: "Source was inspired by target.",
    kind: "associative",
    source_types: [],
    target_types: [],
    is_symmetric: false,
    semantic_parent_slug: "relates_to",
    is_system: true,
  },
  {
    slug: "references",
    label: "References",
    description: "Source cites or points at target.",
    kind: "associative",
    source_types: [],
    target_types: [],
    is_symmetric: false,
    semantic_parent_slug: "relates_to",
    is_system: true,
  },
  {
    slug: "about",
    label: "About",
    description: "Source is about a person.",
    kind: "associative",
    source_types: [],
    target_types: ["person"],
    is_symmetric: false,
    semantic_parent_slug: "relates_to",
    is_system: true,
  },
];
