export { createPool, waitForDb, type Pool, type PoolClient } from "./client.js";
export { migrate } from "./migrate.js";
export { seedSystemOntology } from "./seed.js";
export {
  countDeletedNodesByType,
  countEdgesByRelation,
  countNodesByType,
  countRelationsUsingSemanticParent,
  countTypesUsingParent,
  deleteNodeType,
  deleteRelationType,
  getNodeType,
  getRelationType,
  insertNodeType,
  insertRelationType,
  listNodeTypes,
  listRelationTypes,
  pingDb,
  updateNodeType,
  updateNodeTypeDescription,
  updateRelationType,
  updateRelationTypeDescription,
} from "./queries.js";
export {
  getActivityById,
  getCreateActivityForNode,
  insertActivity,
  listActivity,
  markActivityUndone,
  markNodeDeleteActivitiesIrreversible,
  UNDO_TTL_MS,
} from "./activity.js";
export {
  deleteEdge,
  deleteEdgeById,
  findEdge,
  getEdgeById,
  getNodeById,
  getNodeByIdempotencyKey,
  getNodeByOrigin,
  hasLiveChildOf,
  insertEdge,
  insertNode,
  isChildOfParent,
  listEdgesTouching,
  listIncidentEdges,
  purgeDeletedNodesByType,
  restoreEdge,
  restoreNode,
  restoreNodeSnapshot,
  searchNodes,
  searchTitleLinkCandidates,
  softDeleteNode,
  updateNode,
} from "./nodes.js";
export {
  BLOB_DIR_MODE,
  BLOB_FILE_MODE,
  UPLOAD_DIR_MODE,
  decodeBytesBase64,
  ensureBlobLayout,
  getBlobById,
  getBlobBySha256,
  ingestBlobBytes,
  ingestBlobFromUpload,
  mapBlob,
  readBlobBytes,
  resolveBlobFilePath,
  resolveUploadPath,
  sha256Hex,
  unlinkQuiet,
  type BlobIngestResult,
  type BlobRuntime,
} from "./blobs.js";
export { isForeignKeyViolation, isUniqueViolation, withTransaction, type Queryable } from "./tx.js";
